
import __ASTRO_IMAGE_IMPORT_ZWdUDz from "../../assets/work/bespoke-design-studio/bespoke-design-studio-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbespoke-design-studio.mdx";
import __ASTRO_IMAGE_IMPORT_Z24w2uB from "../../assets/work/bespoke-design-studio/scene-2-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbespoke-design-studio.mdx";
import __ASTRO_IMAGE_IMPORT_1oenzV from "../../assets/work/cvs-redesign/cvs-redesign-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcvs-redesign.mdx";
import __ASTRO_IMAGE_IMPORT_o0Dqo from "../../assets/work/cvs-redesign/cvs-header-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcvs-redesign.mdx";
import __ASTRO_IMAGE_IMPORT_Z14lyb from "../../assets/work/myfrontier-app/myfrontier-app-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmyfrontier-app.mdx";
import __ASTRO_IMAGE_IMPORT_1Fsk7M from "../../assets/work/myfrontier-app/frontier-app-kv.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmyfrontier-app.mdx";
import __ASTRO_IMAGE_IMPORT_VrgqG from "../../assets/work/samsung-redesign/samsung-redesign-carousel.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsamsung-redesign.mdx";
import __ASTRO_IMAGE_IMPORT_ZWiizI from "../../assets/work/samsung-redesign/revamp-kv.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsamsung-redesign.mdx";
export default new Map([["../../assets/work/bespoke-design-studio/bespoke-design-studio-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbespoke-design-studio.mdx", __ASTRO_IMAGE_IMPORT_ZWdUDz], ["../../assets/work/bespoke-design-studio/scene-2-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fbespoke-design-studio.mdx", __ASTRO_IMAGE_IMPORT_Z24w2uB], ["../../assets/work/cvs-redesign/cvs-redesign-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcvs-redesign.mdx", __ASTRO_IMAGE_IMPORT_1oenzV], ["../../assets/work/cvs-redesign/cvs-header-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fcvs-redesign.mdx", __ASTRO_IMAGE_IMPORT_o0Dqo], ["../../assets/work/myfrontier-app/myfrontier-app-thumbnail.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmyfrontier-app.mdx", __ASTRO_IMAGE_IMPORT_Z14lyb], ["../../assets/work/myfrontier-app/frontier-app-kv.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fmyfrontier-app.mdx", __ASTRO_IMAGE_IMPORT_1Fsk7M], ["../../assets/work/samsung-redesign/samsung-redesign-carousel.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsamsung-redesign.mdx", __ASTRO_IMAGE_IMPORT_VrgqG], ["../../assets/work/samsung-redesign/revamp-kv.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2Fsamsung-redesign.mdx", __ASTRO_IMAGE_IMPORT_ZWiizI]]);
		